version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq

    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI

    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    restart: unless-stopped

volumes:
  rabbitmq_data: